lets just do one old password

diff --git a/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb b/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
--- a/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
+++ b/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
@@ -6,54 +6,42 @@ source /var/vcap/packages/python-*/bosh/runtime.env
 
 echo "attempting cassandra admin user password cycle..."
 
-<% if p("ycql.old_cassandra_passwords").length == 1 && p("ycql.old_cassandra_passwords")[0] == p('ycql.cassandra_password') %>
-echo "appears old_cassandra_passwords only has one element, and it's the same value as the intended password. aborting early to save time."
+<% if p("ycql.cassandra_password_old").nil? %>
+echo "cassandra_password_old is not set. aborting early to save time."
 exit 0
 <% end %>
 
-echo "attempting the current intended password set in cqlshrc password to see if it's already set..."
-/var/vcap/packages/yugabyte/bin/cqlsh \
-  --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
-  --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
+<% if p("ycql.cassandra_password_old") == p("ycql.cassandra_password") %>
+echo "cassandra_password_old is the same value as cassandra_password. aborting early to save time."
+exit 0
+<% end %>
 
-failure_on_checking_current=$?
-if [[ "${failure_on_checking_current}" == 0 ]]; then
-  echo "current password appears CONSISTENT with intended password set in cqlshrc. aborting early to save time. if you have an old_cassandra_passwords opsfile or property, you can probably remove that now."
+echo "attempting current cassandra_password to see if it is already set..."
+/var/vcap/packages/yugabyte/bin/cqlsh \
+    --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
+    --execute "LOGIN cassandra '<%= p('ycql.cassandra_password') %>'"
+
+if [[ $? == 0 ]]; then
+  echo "cassandra_password is already in use. aborting early to save time."
   exit 0
-else
-  echo "current configured password did not succeed, trying old_cassandra_passwords..."
-fi
 
-<% p("ycql.old_cassandra_passwords", []).each_with_index do |old_password_attempt, index| %>
-
-echo "attempting to update current password using old_cassandra_password at list index <%= index %>..."
-
+echo "attempting to update cassandra_password using cassandra_password_old..."
 /var/vcap/packages/yugabyte/bin/cqlsh \
   --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
-  --password "<%= old_password_attempt %>" \
+  --password "<%= p("ycql.cassandra_password_old") %>" \
   --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
 
-failure_on_attempt=$?
-if [[ "${failure_on_attempt}" == 0 ]]; then
-
-  echo "password appears to have been set, confirming..."
-  sleep 5
-
+if [[ $? == 0 ]]; then
+  echo "cassandra_password appears to have been set using cassandra_password_old. confirming cassandra_password is in use..."
   /var/vcap/packages/yugabyte/bin/cqlsh \
     --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
-    --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
+    --execute "LOGIN cassandra '<%= p('ycql.cassandra_password') %>'"
 
-  failure_on_confirmation=$?
-  if [[ "${failure_on_confirmation}" == 0 ]]; then
-    echo "set password appears CONSISTENT with intended password set in cqlshrc. success."
+  if [[ $? == 0 ]]; then
+    echo "cassandra_password appears to be working successfully."
     exit 0
   fi
 
-  echo "set password appears INCONSISTENT with intended password set in cqlshrc. aborting."
+  echo "cassandra_password appears to be in an INCONSISTENT state. aborting."
   exit 1
-
 fi
-
-echo "appears old_cassandra_password at list index <%= index %> was invalid, continuing..."
-
-<% end %>
