hooray, was just missing the single tickmarks

diff --git a/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb b/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
--- a/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
+++ b/jobs/yb-tserver/templates/bin/ycql-admin-pw-cycle.sh.erb
@@ -11,6 +11,19 @@ echo "appears old_cassandra_passwords only has one element, and it's the same va
 exit 0
 <% end %>
 
+echo "attempting the current intended password set in cqlshrc password to see if it's already set..."
+/var/vcap/packages/yugabyte/bin/cqlsh \
+  --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
+  --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
+
+failure_on_checking_current=$?
+if [[ "${failure_on_checking_current}" == 0 ]]; then
+  echo "current password appears CONSISTENT with intended password set in cqlshrc. aborting early to save time. if you have an old_cassandra_passwords opsfile or property, you can probably remove that now."
+  exit 0
+else
+  echo "current configured password did not succeed, trying old_cassandra_passwords..."
+fi
+
 <% p("ycql.old_cassandra_passwords", []).each_with_index do |old_password_attempt, index| %>
 
 echo "attempting to update current password using old_cassandra_password at list index <%= index %>..."
@@ -18,16 +31,17 @@ echo "attempting to update current password using old_cassandra_password at list
 /var/vcap/packages/yugabyte/bin/cqlsh \
   --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
   --password "<%= old_password_attempt %>" \
-  --execute "ALTER ROLE cassandra WITH password = <%= p('ycql.cassandra_password') %>'"
+  --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
 
 failure_on_attempt=$?
 if [[ "${failure_on_attempt}" == 0 ]]; then
 
   echo "password appears to have been set, confirming..."
+  sleep 5
 
   /var/vcap/packages/yugabyte/bin/cqlsh \
     --cqlshrc /var/vcap/jobs/yb-tserver/config/cqlshrc \
-    --execute "ALTER ROLE cassandra WITH password = <%= p('ycql.cassandra_password') %>'"
+    --execute "ALTER ROLE cassandra WITH password = '<%= p('ycql.cassandra_password') %>'"
 
   failure_on_confirmation=$?
   if [[ "${failure_on_confirmation}" == 0 ]]; then
