openjdk packaging

diff --git a/packages/openjdk8/packaging b/packages/openjdk8/packaging
--- a/packages/openjdk8/packaging
+++ b/packages/openjdk8/packaging
@@ -1,1 +1,13 @@
-set -e
+#!/bin/bash
+
+set -e -x
+
+cd ${BOSH_INSTALL_TARGET}
+mkdir jre && tar zxvf ${BOSH_COMPILE_TARGET}/openjdk8/openjdk8-*.tar.gz -C jre
+if [[ $? != 0 ]]; then
+  echo "Cannot unpack JRE"
+  exit 1
+fi
+
+# latest JRE release didn't have correct permissions
+chmod -R a+r jre
